"""empty message

Revision ID: 1a0103cd80bc
Revises: 
Create Date: 2024-10-06 22:27:00.579457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0103cd80bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league',
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('league_depth', sa.Integer(), nullable=False),
    sa.Column('league_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('league_id')
    )
    op.create_table('position',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('position_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('region',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('region_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stadium',
    sa.Column('stadium_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('standard_seats', sa.Integer(), nullable=False),
    sa.Column('bleacher_seats', sa.Integer(), nullable=False),
    sa.Column('premium_seats', sa.Integer(), nullable=False),
    sa.Column('club_seats', sa.Integer(), nullable=False),
    sa.Column('box_seats', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('stadium_id')
    )
    op.create_table('trainertype',
    sa.Column('trainertype_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('attribute_increase', sa.String(length=120), nullable=False),
    sa.Column('increase_amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('trainertype_id')
    )
    op.create_table('trainer',
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('trainertype_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trainertype_id'], ['trainertype.trainertype_id'], ),
    sa.PrimaryKeyConstraint('trainer_id')
    )
    op.create_table('team',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('finances', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('stadium_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.league_id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadium.stadium_id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer.trainer_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('match',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=False),
    sa.Column('away_goals', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=120), nullable=False),
    sa.Column('played', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.team_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.team_id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['league.league_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('player',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('mentality', sa.String(length=42), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('passes', sa.Integer(), nullable=False),
    sa.Column('shoot', sa.Integer(), nullable=False),
    sa.Column('stop_ball', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('physique', sa.Integer(), nullable=False),
    sa.Column('precision', sa.Integer(), nullable=False),
    sa.Column('goalkeep', sa.Integer(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.region_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('salt', sa.String(length=200), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.region_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('position_player',
    sa.Column('positionplayer_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.position_id'], ),
    sa.PrimaryKeyConstraint('positionplayer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position_player')
    op.drop_table('user')
    op.drop_table('player')
    op.drop_table('match')
    op.drop_table('team')
    op.drop_table('trainer')
    op.drop_table('trainertype')
    op.drop_table('stadium')
    op.drop_table('region')
    op.drop_table('position')
    op.drop_table('league')
    # ### end Alembic commands ###
